spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/Test
    username : karim
    password : password
    driver-class-name : org.postgresql.Driver
  jpa:
    properties.hibernate.default_schema : test_schema
    show-sql : true
flyway:
  schemas : test_schema
  enabled : true
  validateOnMigrate : false
  check-location : false
  locations : db/migration/postgre
  baseline-on-migrate : true