spring:
  h2:
    console:
      enabled : true
      path : /h2
  datasource:
    url : jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username : sa
    password :
    driver-class-name : org.h2.Driver
  jpa:
    properties.hibernate.default_schema : TEST_SCHEMA
flyway:
  schemas : TEST_SCHEMA
  enabled : true
  validateOnMigrate : false
  check-location : false
  locations : db/migration/h2